name: Build and Push Image to Registry
description: Push Docker image to GCP registry
inputs:
  gcp-service-account-key:
    description: GCP Service Account Key (JSON format)
    required: true
  image-tag:
    description: Docker image tag
    required: true
  image-name:
    description: Docker image name
    required: true
  working-directory:
    description: Path of the folder containing the Dockerfile
    required: true
    default: apps
  registry-artifact:
    description: Artifact registry name
    required: true
  registry-project:
    description: GCP Project of the artifact registry
    required: true
    default: fiebel-video-nonprod
  registry-name:
    description: Registry DNS name
    required: true
    default: europe-west2-docker.pkg.dev
runs:
  using: "composite"
  steps:
    - name: Install Docker
      uses: docker/setup-buildx-action@v1.6.0
    - name: Docker login
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ inputs.registry-name }}
        username: _json_key_base64
        password: ${{ inputs.gcp-service-account-key }}
    - name: Docker build
      working-directory: ${{ inputs.working-directory }}
      run: docker build . -t ${{ inputs.registry-name }}/${{ inputs.registry-project }}/${{ inputs.registry-artifact }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
    - name: Push Image
      working-directory: ${{ inputs.working-directory }}
      run: docker push ${{ inputs.registry-name }}/${{ inputs.registry-project }}/${{ inputs.registry-artifact }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
