name: Terraform Plan
description: Run Terraform Plan
inputs:
  gcp-service-account-key:
    description: GCP Service Account Key (JSON format)
    required: true
  environment:
    description: "Project Environment: prod, nonprod"
    required: true
  tf-api-token:
    description: Terraform Cloud API Token
    required: true
  terraform-version:
    description: Terraform release version
    required: true
  working-directory:
    description: Location of terraform root folder
    required: true
    default: infrastructure
runs:
  using: "composite"
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: ${{ inputs.terraform-version }}
        cli_config_credentials_token: ${{ inputs.tf-api-token }}
        terraform_wrapper: false
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ inputs.gcp-service-account-key }}
        export_default_credentials: true
    - name: Terraform Init
      working-directory: ${{ inputs.working-directory }}
      env:
        TF_WORKSPACE: ${{ inputs.environment }}
      run: terraform init
    - name: Terraform Select Workspace
      working-directory: ${{ inputs.working-directory }}
      env:
        environment: ${{ inputs.environment }}
      run: terraform workspace select $environment
    - name: Terraform Validate
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate
    - name: Terraform Plan
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan
