name: Update Cloudrun image tags
description: Update Tags of cloudrun apps
inputs:
  environment:
    description: "Project Environment: nonprod, prod"
    required: true
  push:
    description: Do you want to push the changes?
    required: true
    default: false
  working-directory:
    description: Location of terraform root folder
    required: true
    default: infrastructure
  image-name:
    description: image to be updated
    required: true
  image-tag:
    description: new image tag to update cloudrun apps with
  registry-name:
    description: Registry DNS name
    default: europe-west2-docker.pkg.dev
runs:
  using: "composite"
  steps:
    - name: Bump up image versions
      working-directory: ${{ inputs.working-directory }}
      env:
        TAG: ${{ inputs.image-tag }}
        NAME: ${{ inputs.image-name }}
      run: |
        sed -i 's/\/'${NAME}':.*/\/'${NAME}':'${TAG}'"/g' cloudrun.tf
      shell: bash
    - name: Update cloudrun apps
      working-directory: ${{ inputs.working-directory }}
      env:
        NAME: ${{ inputs.image-name }}
        TAG: ${{ inputs.image-tag }}
        REGISTRY: ${{ inputs.registry-name }}
      run: |
        set -e
        gcloud run deploy --platform managed --region $REGION --project $PROJECT --image $REGISTRY/$PROJECT_ID/$NAME:$TAG
      shell: bash
    - name: commit versions
      run: |
        git config --global user.name "fiebel-cicd"
        git commit -am ':robot: auto bump cloudrun apps version tag in ${{ inputs.environment }}'
      shell: bash
    - name: push
      if: inputs.push == 'true'
      run: git push
      shell: bash
