name: Deploy
on:
  push:
    branches:
      - main
jobs:
  init:
    name: Initialize
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: fetch last version of the PR branch
        run: git fetch origin ${GITHUB_HEAD_REF} && git checkout ${GITHUB_HEAD_REF}
      - name: Get Files Changes Info
        id: info
        uses: ./.github/actions/files-change-info
    outputs:
      terraform-changes: ${{ steps.info.outputs.terraform-changes }}

  terragrunt-apply-nonprod:
    name: Terraform Apply NONPROD
    runs-on: ubuntu-20.04
    needs:
      - init
    if: always() && needs.init.outputs.terraform-changes == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: fetch branch
        run: git fetch origin ${GITHUB_HEAD_REF} && git checkout ${GITHUB_HEAD_REF}
      - name: Distribute functions
        run: bash scripts/zp_functions.sh -xe
        shell: bash
      - name: terraform apply
        uses: ./.github/actions/terraform/apply
        with:
          gcp-service-account-key: ${{ secrets.GCP_NONPROD_CREDENTIALS }}
          terraform-version: 1.1.7
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          environment: nonprod
